== Timing Diagram

This is still under construction. You can propose new features if you need some.


== Declaring element or participant

You declare participant using the following keywords, depending on how you want them to be drawn.

|===
| Keyword | Description

| `+analog+`
| An `+analog+` signal is continuous, and the values are linearly interpolated between the given setpoints

| `+binary+`
| A `+binary+` signal restricted to only 2 states

| `+clock+`
| A `+clocked+` signal that repeatedly transitions from high to low, with a `+period+`, and an optional `+pulse+` and `+offset+`

| `+concise+`
| A simplified `+concise+` signal designed to show the movement of data (great for messages)

| `+robust+`
| A `+robust+` complex line signal designed to show the transition from one state to another (can have many states)

|===



You define state change using the `+@+` notation, and the `+is+` verb.

<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU is Waiting
WB is Processing

@300
WB is Waiting
@enduml
</plantuml>

<plantuml>
@startuml
clock   "Clock_0"   as C0 with period 50
clock   "Clock_1"   as C1 with period 50 pulse 15 offset 10
binary  "Binary"  as B
concise "Concise" as C
robust  "Robust"  as R
analog  "Analog"  as A


@0
C is Idle
R is Idle
A is 0

@100
B is high
C is Waiting
R is Processing
A is 3

@300
R is Waiting
A is 1
@enduml
</plantuml>

__[Ref. https://forum.plantuml.net/14631[QA-14631], https://forum.plantuml.net/14647[QA-14647] and https://forum.plantuml.net/11288/mixed-signal-timing-diagram[QA-11288]]__


== Binary and Clock

It's also possible to have binary and clock signal, using the following keywords:

* `+binary+`
* `+clock+`

<plantuml>
@startuml
clock clk with period 1
binary "Enable" as EN

@0
EN is low

@5
EN is high

@10
EN is low
@enduml
</plantuml>


== Adding message

You can add message using the following syntax.

<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU -> WB : URL
WU is Waiting
WB is Processing

@300
WB is Waiting
@enduml
</plantuml>



== Relative time

It is possible to use relative time with `+@+`.
<plantuml>
@startuml
robust "DNS Resolver" as DNS
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle
DNS is Idle

@+100
WU -> WB : URL
WU is Waiting
WB is Processing

@+200
WB is Waiting
WB -> DNS@+50 : Resolve URL

@+100
DNS is Processing

@+300
DNS is Idle
@enduml
</plantuml>



== Anchor Points

Instead of using absolute or relative time on an absolute time you can define a time as an anchor point by using the `+as+` keyword and starting the name with a `+:+`. 

----
@XX as :<anchor point name>
----


<plantuml>
@startuml
clock clk with period 1
binary "enable" as EN
concise "dataBus" as db

@0 as :start
@5 as :en_high 
@10 as :en_low
@:en_high-2 as :en_highMinus2

@:start
EN is low
db is "0x0000"

@:en_high
EN is high

@:en_low
EN is low

@:en_highMinus2
db is "0xf23a"

@:en_high+6
db is "0x0000"
@enduml
</plantuml>


== Participant oriented

Rather than declare the diagram in chronological order, you can define it by participant.

<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@WB
0 is idle
+200 is Proc.
+100 is Waiting

@WU
0 is Waiting
+500 is ok
@enduml
</plantuml>



== Setting scale
You can also set a specific scale.
<plantuml>
@startuml
concise "Web User" as WU
scale 100 as 50 pixels

@WU
0 is Waiting
+500 is ok
@enduml
</plantuml>

When using absolute Times/Dates, 1 "tick" is equivalent to 1 second.
<plantuml>
@startuml
concise "Season" as S
'30 days is scaled to 50 pixels
scale 2592000 as 50 pixels

@2000/11/01
S is "Winter"

@2001/02/01
S is "Spring"

@2001/05/01
S is "Summer"

@2001/08/01
S is "Fall"
@enduml
</plantuml>


== Initial state
You can also define an inital state.
<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

WB is Initializing
WU is Absent

@WB
0 is idle
+200 is Processing
+100 is Waiting

@WU
0 is Waiting
+500 is ok
@enduml
</plantuml>



== Intricated state

A signal could be in some undefined state.

=== Intricated or undefined robust state
<plantuml>
@startuml
robust "Signal1" as S1
robust "Signal2" as S2
S1 has 0,1,2,hello
S2 has 0,1,2
@0
S1 is 0
S2 is 0
@100
S1 is {0,1} #SlateGrey
S2 is {0,1}
@200
S1 is 1
S2 is 0
@300
S1 is hello
S2 is {0,2}
@enduml
</plantuml>

=== Intricated or undefined binary state
<plantuml>
@startuml
clock "Clock" as C with period 2
binary "Enable" as EN

@0
EN is low
@1
EN is high
@3
EN is low
@5
EN is {low,high}
@10
EN is low
@enduml
</plantuml>

__[Ref. https://forum.plantuml.net/11936[QA-11936] and https://forum.plantuml.net/15933[QA-15933]]__


== Hidden state

It is also possible to hide some state.

<plantuml>
@startuml
concise "Web User" as WU

@0
WU is {-}

@100
WU is A1

@200
WU is {-}

@300
WU is {hidden}

@400
WU is A3

@500
WU is {-}
@enduml
</plantuml>

<plantuml>
@startuml
scale 1 as 50 pixels

concise state0
concise substate1
robust bit2

bit2 has HIGH,LOW

@state0
0 is 18_start
6 is s_dPause
8 is 10_data
14 is {hidden}

@substate1
0 is sSeq
4 is sPause
6 is {hidden}
8 is dSeq
12 is dPause
14 is {hidden}

@bit2
0 is HIGH
2 is LOW
4 is {hidden}
8 is HIGH
10 is LOW
12 is {hidden}
@enduml
</plantuml>
__[Ref. https://forum.plantuml.net/12222[QA-12222]]__


== Hide time axis

It is possible to hide time axis.

<plantuml>
@startuml
hide time-axis
concise "Web User" as WU

WU is Absent

@WU
0 is Waiting
+500 is ok
@enduml
</plantuml>


== Using Time and Date

It is possible to use time or date.


<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@2019/07/02
WU is Idle
WB is Idle

@2019/07/04
WU is Waiting : some note
WB is Processing : some other note

@2019/07/05
WB is Waiting
@enduml
</plantuml>



<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@1:15:00
WU is Idle
WB is Idle

@1:16:30
WU is Waiting : some note
WB is Processing : some other note

@1:17:30
WB is Waiting
@enduml
</plantuml>





== Adding constraint
It is possible to display time constraints on the diagrams.
<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

WB is Initializing
WU is Absent

@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}

@WU
0 is Waiting
+500 is ok
@200 <-> @+150 : {150 ms}
@enduml
</plantuml>




== Highlighted period

You can higlight a part of diagram.

<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU -> WB : URL
WU is Waiting #LightCyan;line:Aqua

@200
WB is Proc.

@300
WU -> WB@350 : URL2
WB is Waiting

@+200
WU is ok

@+200
WB is Idle

highlight 200 to 450 #Gold;line:DimGrey : This is my caption
highlight 600 to 700 : This is another\nhighlight
@enduml
</plantuml>


__[Ref. https://forum.plantuml.net/10868/highlighted-periods-in-timing-diagrams[QA-10868]]__


== Using notes

You can use the `+note top of+` and `+note bottom of+`
keywords to define notes related to a single object or participant __(available only for__ `+concise+` __ object).__

<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU is Waiting
WB is Processing
note top of WU : first note\non several\nlines
note bottom of WU : second note\non several\nlines

@300
WB is Waiting
@enduml
</plantuml>

__[Ref. https://forum.plantuml.net/6877[QA-6877]]__


== Adding texts

You can optionally add a title, a header, a footer, a legend and a caption:

<plantuml>
@startuml
Title This is my title
header: some header
footer: some footer
legend
Some legend
end legend
caption some caption

robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU is Waiting
WB is Processing

@300
WB is Waiting
@enduml
</plantuml>


== Complete example


Thanks to https://twitter.com/arosien[Adam Rosien] for this example.

<plantuml>
@startuml
concise "Client" as Client
concise "Server" as Server
concise "Response freshness" as Cache

Server is idle
Client is idle

@Client
0 is send
Client -> Server@+25 : GET
+25 is await
+75 is recv
+25 is idle
+25 is send
Client -> Server@+25 : GET\nIf-Modified-Since: 150
+25 is await
+50 is recv
+25 is idle
@100 <-> @275 : no need to re-request from server

@Server
25 is recv
+25 is work
+25 is send
Server -> Client@+25 : 200 OK\nExpires: 275
+25 is idle
+75 is recv
+25 is send
Server -> Client@+25 : 304 Not Modified
+25 is idle

@Cache
75 is fresh
+200 is stale
@enduml
</plantuml>


== Digital Example

<plantuml>
@startuml
scale 5 as 150 pixels

clock clk with period 1
binary "enable" as en
binary "R/W" as rw
binary "data Valid" as dv
concise "dataBus" as db
concise "address bus" as addr

@6 as :write_beg
@10 as :write_end

@15 as :read_beg
@19 as :read_end


@0
en is low
db is "0x0"
addr is "0x03f"
rw is low
dv is 0

@:write_beg-3
 en is high
@:write_beg-2
 db is "0xDEADBEEF"
@:write_beg-1
dv is 1
@:write_beg
rw is high


@:write_end
rw is low
dv is low
@:write_end+1
rw is low
db is "0x0"
addr is "0x23"

@12
dv is high
@13 
db is "0xFFFF"

@20
en is low
dv is low
@21 
db is "0x0"

highlight :write_beg to :write_end #Gold:Write
highlight :read_beg to :read_end #lightBlue:Read

db@:write_beg-1 <-> @:write_end : setup time
db@:write_beg-1 -> addr@:write_end+1 : hold
@enduml
</plantuml>


== Adding color

You can add link::color[color].

<plantuml>
@startuml
concise "LR" as LR
concise "ST" as ST

LR is AtPlace #palegreen
ST is AtLoad #gray

@LR
0 is Lowering
100 is Lowered #pink
350 is Releasing
 
@ST
200 is Moving
@enduml
</plantuml>

__[Ref. https://forum.plantuml.net/5776[QA-5776]]__


== Using (global) style

=== Without style __(by default)__
<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

WB is Initializing
WU is Absent

@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}

@WU
0 is Waiting
+500 is ok
@200 <-> @+150 : {150 ms}
@enduml
</plantuml>


=== With style

You can use link::style-evolution[style] to change rendering of elements.

<plantuml>
@startuml
<style>
timingDiagram {
  document {
    BackGroundColor SandyBrown
  }
 constraintArrow {
  LineStyle 2-1
  LineThickness 3
  LineColor Blue
 }
}
</style>
robust "Web Browser" as WB
concise "Web User" as WU

WB is Initializing
WU is Absent

@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}

@WU
0 is Waiting
+500 is ok
@200 <-> @+150 : {150 ms}
@enduml
</plantuml>

__[Ref.  https://forum.plantuml.net/14340/color-of-arrow-in-timing-diagram[QA-14340]]__


== Applying Colors to specific lines

You can use the `+<style>+` tags and sterotyping to give a name to line attributes.

<plantuml>
@startuml
<style>
timingDiagram {
  .red {
    LineColor red
  }
  .blue {
    LineColor blue
    LineThickness 5
  }
}
</style>

clock clk with period 1
binary "Input Signal 1"  as IS1
binary "Input Signal 2"  as IS2 <<blue>>
binary "Output Signal 1" as OS1 <<red>>

@0
IS1 is low
IS2 is high
OS1 is low
@2
OS1 is high
@4
OS1 is low
@5
IS1 is high
OS1 is high
@6
IS2 is low
@10
IS1 is low
OS1 is low
@enduml
</plantuml>

__[https://forum.plantuml.net/15870/timing-diagram-assign-different-colors-single-participants?show=15870#q15870[Ref. QA-15870]]__


== Compact mode

You can use `+compact+` command to compact the timing layout.

=== By default
<plantuml>
@startuml
robust "Web Browser" as WB
concise "Web User" as WU
robust "Web Browser2" as WB2

@0
WU is Waiting
WB is Idle
WB2 is Idle

@200
WB is Proc.

@300
WB is Waiting
WB2 is Waiting

@500
WU is ok

@700
WB is Idle
@enduml
</plantuml>

==== Global mode with `+mode compact+`
<plantuml>
@startuml
mode compact
robust "Web Browser" as WB
concise "Web User" as WU
robust "Web Browser2" as WB2

@0
WU is Waiting
WB is Idle
WB2 is Idle

@200
WB is Proc.

@300
WB is Waiting
WB2 is Waiting

@500
WU is ok

@700
WB is Idle
@enduml
</plantuml>

=== Local mode with only `+compact+` on element
<plantuml>
@startuml
compact robust "Web Browser" as WB
compact concise "Web User" as WU
robust "Web Browser2" as WB2

@0
WU is Waiting
WB is Idle
WB2 is Idle

@200
WB is Proc.

@300
WB is Waiting
WB2 is Waiting

@500
WU is ok

@700
WB is Idle
@enduml
</plantuml>

__[Ref. https://forum.plantuml.net/11130/is-there-a-compact-timing-diagram[QA-11130]]__


