@startuml
set separator none
title System Landscape

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("Big Bank plc", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "Big Bank plc", $tags="Big Bank plc") {
  Person(CustomerServiceStaff, "Customer Service Staff", "Customer service staff within the bank.", $tags="")
  Person(BackOfficeStaff, "Back Office Staff", "Administration and support staff within the bank.", $tags="")
  System(MainframeBankingSystem, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.", $tags="")
  System(EmailSystem, "E-mail System", "The internal Microsoft Exchange e-mail system.", $tags="")
  System(ATM, "ATM", "Allows customers to withdraw cash.", $tags="")
  System(InternetBankingSystem, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.", $tags="")
}

Person(PersonalBankingCustomer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.", $tags="")

Rel_D(PersonalBankingCustomer, InternetBankingSystem, "Views account balances, and makes payments using", $tags="")
Rel_D(InternetBankingSystem, MainframeBankingSystem, "Gets account information from, and makes payments using", $tags="")
Rel_D(InternetBankingSystem, EmailSystem, "Sends e-mail using", $tags="")
Rel_D(EmailSystem, PersonalBankingCustomer, "Sends e-mails to", $tags="")
Rel_D(PersonalBankingCustomer, CustomerServiceStaff, "Asks questions to", "Telephone", $tags="")
Rel_D(CustomerServiceStaff, MainframeBankingSystem, "Uses", $tags="")
Rel_D(PersonalBankingCustomer, ATM, "Withdraws cash using", $tags="")
Rel_D(ATM, MainframeBankingSystem, "Uses", $tags="")
Rel_D(BackOfficeStaff, MainframeBankingSystem, "Uses", $tags="")

SHOW_LEGEND(true)
@enduml
