@startuml
set separator none
title Internet Banking System - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("Big Bank plc", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "Big Bank plc", $tags="Big Bank plc") {
  System(MainframeBankingSystem, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.", $tags="")
  System(EmailSystem, "E-mail System", "The internal Microsoft Exchange e-mail system.", $tags="")
  System(InternetBankingSystem, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.", $tags="")
}

Person(PersonalBankingCustomer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.", $tags="")

Rel_D(PersonalBankingCustomer, InternetBankingSystem, "Views account balances, and makes payments using", $tags="")
Rel_D(InternetBankingSystem, MainframeBankingSystem, "Gets account information from, and makes payments using", $tags="")
Rel_D(InternetBankingSystem, EmailSystem, "Sends e-mail using", $tags="")
Rel_D(EmailSystem, PersonalBankingCustomer, "Sends e-mails to", $tags="")

SHOW_LEGEND(true)
@enduml
